# Generated by Django 6.1.1 on 2026-09-22 14:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
