# Generated by Django 6.1.1 on 2026-09-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_articlecontent_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
